# Generated by Django 5.1.2 on 2024-10-12 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits long', regex='^\\d{10}$')]),
        ),
    ]
